title: Rodrigo Moutinho
logo: /profile.jpg
description: >
  Data Analytics Manager @Nestlé | PhD in Data Science Candidate  
  Specializing in NLP, Machine Learning, and Data Engineering  
  Passionate about building intelligent data-driven products.

theme: jekyll-theme-minimal
show_downloads: false
github:
  is_project_page: false
